-- =============================================================================
-- Taxi DJ — FIX / UPDATE DATABASE (safe to run any time, as often as needed)
--
-- Brings a Taxi DJ database fully up to date, whatever updates it is missing.
-- Supabase → SQL Editor → New query → paste this whole file → Run.
-- Generated by scripts/build-fix-database.mjs from supabase/migrations/.
-- =============================================================================

-- ---------------------------------------------------------------- 20260925000000_passenger_remove_and_replay.sql
-- =============================================================================
-- Taxi DJ — passengers can remove their own songs; 10-song default limit
--
-- * passenger_remove_request(): a passenger removes one of their own songs
--   that hasn't played yet. Removed songs don't count toward the limit, so
--   the passenger can pick something else.
-- * removed_by records who removed a song ('passenger' or 'driver'; NULL for
--   rows removed by the driver before this migration).
-- * Default per-passenger limit raised from 3 to 10 for new drivers/rides.
--   Existing drivers keep their chosen setting (Settings → Max songs).
--
-- Replays need no new function: a passenger re-requests a played song via
-- add_song_request, which already enforces the limit and duplicate rules.
-- =============================================================================

alter table public.song_requests
  add column if not exists removed_by text check (removed_by in ('passenger', 'driver'));

alter table public.drivers alter column max_requests_per_passenger set default 10;
alter table public.rides alter column max_requests_per_passenger set default 10;

-- Mark driver removals too, so the passenger UI can tell them apart.
create or replace function public.song_requests_mark_driver_removal() returns trigger
language plpgsql as $$
begin
  if new.status = 'removed' and old.status <> 'removed' and new.removed_by is null then
    new.removed_by := 'driver';
  end if;
  return new;
end;
$$;

drop trigger if exists song_requests_mark_driver_removal on public.song_requests;
create trigger song_requests_mark_driver_removal
  before update of status on public.song_requests
  for each row execute function public.song_requests_mark_driver_removal();

create or replace function public.passenger_remove_request(p_request_id uuid)
returns public.song_requests
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := auth.uid();
  v_req public.song_requests;
  v_ride public.rides;
begin
  if v_uid is null then perform public.taxidj_error('NOT_AUTHENTICATED'); end if;

  select r.* into v_req
    from public.song_requests r
    join public.passengers p on p.id = r.passenger_id
   where r.id = p_request_id and p.session_identifier = v_uid;
  if not found then perform public.taxidj_error('REQUEST_NOT_FOUND'); end if;

  -- Same lock as the driver's queue changes, so they can't race.
  select * into v_ride from public.rides where id = v_req.ride_id for update;
  if not public.ride_is_open(v_ride) then perform public.taxidj_error('RIDE_ENDED'); end if;

  select * into v_req from public.song_requests where id = p_request_id;
  if v_req.status not in ('pending', 'queued') then
    perform public.taxidj_error('INVALID_TRANSITION');
  end if;

  update public.song_requests
     set status = 'removed', removed_by = 'passenger'
   where id = v_req.id
  returning * into v_req;

  return v_req;
end;
$$;

revoke execute on function public.passenger_remove_request(uuid) from public, anon, authenticated;
grant execute on function public.passenger_remove_request(uuid) to authenticated;
revoke execute on function public.song_requests_mark_driver_removal() from public, anon, authenticated;

-- ---------------------------------------------------------------- 20260926000000_driver_settings_sync.sql
-- =============================================================================
-- Taxi DJ — driver settings saved to the account and applied immediately
--
-- * Songs per passenger can now be set from 1 to 50 (was 1–10).
-- * playback_mode ('embedded' = Taxi DJ player, 'external' = YouTube app) is
--   stored on the driver so it follows the account across devices/sessions.
-- * update_driver_settings() also applies the car name, approval mode and
--   song limit to the driver's active ride, so changes take effect now
--   instead of only on the next ride.
-- =============================================================================

alter table public.drivers drop constraint if exists drivers_max_requests_per_passenger_check;
alter table public.drivers add constraint drivers_max_requests_per_passenger_check
  check (max_requests_per_passenger between 1 and 50);

alter table public.rides drop constraint if exists rides_max_requests_per_passenger_check;
alter table public.rides add constraint rides_max_requests_per_passenger_check
  check (max_requests_per_passenger between 1 and 50);

alter table public.drivers
  add column if not exists playback_mode text not null default 'embedded'
    check (playback_mode in ('embedded', 'external'));

drop function if exists public.update_driver_settings(text, boolean, integer);

create or replace function public.update_driver_settings(
  p_display_name text,
  p_auto_approve boolean,
  p_max_requests_per_passenger integer,
  p_playback_mode text default null
) returns public.drivers
language plpgsql security definer set search_path = '' as $$
declare
  v_driver public.drivers;
  v_name text := btrim(coalesce(p_display_name, ''));
begin
  perform public.ensure_driver();

  if char_length(v_name) < 1 or char_length(v_name) > 40 then
    perform public.taxidj_error('INVALID_DISPLAY_NAME');
  end if;
  if p_max_requests_per_passenger is null
     or p_max_requests_per_passenger not between 1 and 50 then
    perform public.taxidj_error('INVALID_REQUEST_LIMIT');
  end if;
  if p_playback_mode is not null and p_playback_mode not in ('embedded', 'external') then
    perform public.taxidj_error('INVALID_ACTION');
  end if;

  update public.drivers
     set display_name = v_name,
         auto_approve = coalesce(p_auto_approve, auto_approve),
         max_requests_per_passenger = p_max_requests_per_passenger,
         playback_mode = coalesce(p_playback_mode, playback_mode)
   where id = auth.uid()
  returning * into v_driver;

  -- Apply to the ride in progress too.
  update public.rides
     set name = v_driver.display_name,
         auto_approve = v_driver.auto_approve,
         max_requests_per_passenger = v_driver.max_requests_per_passenger
   where driver_id = v_driver.id and status = 'active';

  return v_driver;
end;
$$;

create or replace function public.set_playback_mode(p_mode text) returns public.drivers
language plpgsql security definer set search_path = '' as $$
declare
  v_driver public.drivers;
begin
  perform public.ensure_driver();
  if p_mode is null or p_mode not in ('embedded', 'external') then
    perform public.taxidj_error('INVALID_ACTION');
  end if;
  update public.drivers set playback_mode = p_mode
   where id = auth.uid()
  returning * into v_driver;
  return v_driver;
end;
$$;

revoke execute on function
  public.update_driver_settings(text, boolean, integer, text),
  public.set_playback_mode(text)
from public, anon, authenticated;
grant execute on function
  public.update_driver_settings(text, boolean, integer, text),
  public.set_playback_mode(text)
to authenticated;

-- ---------------------------------------------------------------- 20260927000000_youtube_handoff.sql
-- =============================================================================
-- Taxi DJ — hand songs to the YouTube / YouTube Music app in batches
--
-- YouTube apps can't be told to "add to queue" by another app, so the driver
-- sends songs as a temporary YouTube playlist. This tracks which songs were
-- already sent, so the next hand-off only sends the new ones.
--
-- driver_send_to_youtube(ride, ids):
--   * songs sent in an earlier batch (or playing) that aren't in this batch
--     are marked played — the driver sends a new batch once the previous one
--     has finished;
--   * every song in this batch gets sent_to_youtube_at = now();
--   * the first song of the batch becomes "playing", the rest stay queued.
-- =============================================================================

alter table public.song_requests add column if not exists sent_to_youtube_at timestamptz;

create or replace function public.driver_send_to_youtube(p_ride_id uuid, p_request_ids uuid[])
returns setof public.song_requests
language plpgsql security definer set search_path = '' as $$
declare
  v_ride public.rides;
  v_first uuid := p_request_ids[1];
begin
  select * into v_ride from public.rides
   where id = p_ride_id and driver_id = auth.uid()
   for update;
  if not found then perform public.taxidj_error('RIDE_NOT_FOUND'); end if;
  if not public.ride_is_open(v_ride) then perform public.taxidj_error('RIDE_ENDED'); end if;

  if v_first is null or exists (
    select 1 from unnest(p_request_ids) as ids(id)
     where not exists (
       select 1 from public.song_requests r
        where r.id = ids.id and r.ride_id = p_ride_id and r.status in ('queued', 'playing')
     )
  ) then
    perform public.taxidj_error('INVALID_TRANSITION');
  end if;

  -- The previous batch has finished playing in YouTube.
  update public.song_requests
     set status = 'played'
   where ride_id = p_ride_id
     and not (id = any (p_request_ids))
     and (status = 'playing' or (status = 'queued' and sent_to_youtube_at is not null));

  update public.song_requests
     set sent_to_youtube_at = now()
   where id = any (p_request_ids);

  update public.song_requests
     set status = 'playing', started_at = now()
   where id = v_first and status <> 'playing';

  return query
    select * from public.song_requests
     where id = any (p_request_ids)
     order by array_position(p_request_ids, id);
end;
$$;

revoke execute on function public.driver_send_to_youtube(uuid, uuid[]) from public, anon, authenticated;
grant execute on function public.driver_send_to_youtube(uuid, uuid[]) to authenticated;

-- ---------------------------------------------------------------- 20260928000000_keep_songs_in_queue.sql
-- =============================================================================
-- Taxi DJ — songs stay in the ride's queue until removed or the ride ends
--
-- * Sending songs to YouTube no longer marks earlier songs as played; every
--   song stays in the list (with its status) for the whole ride.
-- * Drivers can remove any song (waiting, playing or played) from the list.
--   Passengers can still remove their own songs that haven't played yet.
-- =============================================================================

create or replace function public.driver_update_request(p_request_id uuid, p_action text)
returns public.song_requests
language plpgsql security definer set search_path = '' as $$
declare
  v_req public.song_requests;
  v_ride public.rides;
  v_other public.song_requests;
  v_pos integer;
begin
  select * into v_req from public.song_requests where id = p_request_id;
  if not found then perform public.taxidj_error('REQUEST_NOT_FOUND'); end if;

  -- Lock the ride: serialises all queue changes for this ride.
  select * into v_ride from public.rides
   where id = v_req.ride_id and driver_id = auth.uid()
   for update;
  if not found then perform public.taxidj_error('REQUEST_NOT_FOUND'); end if;
  if not public.ride_is_open(v_ride) then perform public.taxidj_error('RIDE_ENDED'); end if;

  -- Re-read under the ride lock.
  select * into v_req from public.song_requests where id = p_request_id;

  case p_action
    when 'approve' then
      if v_req.status <> 'pending' then perform public.taxidj_error('INVALID_TRANSITION'); end if;
      update public.song_requests set status = 'queued' where id = v_req.id returning * into v_req;

    when 'reject' then
      if v_req.status <> 'pending' then perform public.taxidj_error('INVALID_TRANSITION'); end if;
      update public.song_requests set status = 'rejected' where id = v_req.id returning * into v_req;

    when 'remove' then
      -- Drivers can remove any song from the ride's list, including played ones.
      if v_req.status not in ('pending', 'queued', 'playing', 'played') then
        perform public.taxidj_error('INVALID_TRANSITION');
      end if;
      update public.song_requests set status = 'removed' where id = v_req.id returning * into v_req;

    when 'play' then
      if v_req.status not in ('pending', 'queued', 'played') then
        perform public.taxidj_error('INVALID_TRANSITION');
      end if;
      if v_req.status = 'played' and exists (
        select 1 from public.song_requests
         where ride_id = v_req.ride_id and youtube_video_id = v_req.youtube_video_id
           and status in ('pending', 'queued') and id <> v_req.id
      ) then
        perform public.taxidj_error('DUPLICATE_REQUEST');
      end if;
      update public.song_requests set status = 'played'
       where ride_id = v_req.ride_id and status = 'playing';
      update public.song_requests set status = 'playing', started_at = now()
       where id = v_req.id returning * into v_req;

    when 'finish' then
      if v_req.status <> 'playing' then perform public.taxidj_error('INVALID_TRANSITION'); end if;
      update public.song_requests set status = 'played' where id = v_req.id returning * into v_req;

    when 'move_up', 'move_down' then
      if v_req.status not in ('pending', 'queued') then perform public.taxidj_error('INVALID_TRANSITION'); end if;
      if p_action = 'move_up' then
        select * into v_other from public.song_requests
         where ride_id = v_req.ride_id and status in ('pending', 'queued')
           and position < v_req.position
         order by position desc limit 1;
      else
        select * into v_other from public.song_requests
         where ride_id = v_req.ride_id and status in ('pending', 'queued')
           and position > v_req.position
         order by position asc limit 1;
      end if;
      if found then
        v_pos := v_req.position;
        update public.song_requests set position = v_other.position where id = v_req.id
          returning * into v_req;
        update public.song_requests set position = v_pos where id = v_other.id;
      end if;

    else
      perform public.taxidj_error('INVALID_ACTION');
  end case;

  return v_req;
end;
$$;

create or replace function public.driver_send_to_youtube(p_ride_id uuid, p_request_ids uuid[])
returns setof public.song_requests
language plpgsql security definer set search_path = '' as $$
declare
  v_ride public.rides;
  v_first uuid := p_request_ids[1];
begin
  select * into v_ride from public.rides
   where id = p_ride_id and driver_id = auth.uid()
   for update;
  if not found then perform public.taxidj_error('RIDE_NOT_FOUND'); end if;
  if not public.ride_is_open(v_ride) then perform public.taxidj_error('RIDE_ENDED'); end if;

  -- Any song still in the ride's list can be sent (including played ones,
  -- for "play the whole ride playlist").
  if v_first is null or exists (
    select 1 from unnest(p_request_ids) as ids(id)
     where not exists (
       select 1 from public.song_requests r
        where r.id = ids.id and r.ride_id = p_ride_id
          and r.status in ('pending', 'queued', 'playing', 'played')
     )
  ) then
    perform public.taxidj_error('INVALID_TRANSITION');
  end if;

  update public.song_requests
     set sent_to_youtube_at = now()
   where id = any (p_request_ids);

  -- The first song of the batch is now playing (only one can play at once).
  if (select status from public.song_requests where id = v_first) <> 'playing' then
    update public.song_requests set status = 'played'
     where ride_id = p_ride_id and status = 'playing';
    update public.song_requests set status = 'playing', started_at = now()
     where id = v_first;
  end if;

  return query
    select * from public.song_requests
     where id = any (p_request_ids)
     order by array_position(p_request_ids, id);
end;
$$;

-- ---------------------------------------------------------------- 20260929000000_driver_add_song.sql
-- =============================================================================
-- Taxi DJ — the driver can add songs to their own ride's queue
--
-- driver_add_song(): like add_song_request, but for the ride's driver.
-- * No per-passenger limit and no approval step (driver songs are queued).
-- * Duplicate and video-ID checks still apply.
-- * Songs are attributed to a "Driver" passenger row for this ride (created
--   on first use), so every request keeps a requester. The UI hides this row
--   from the passenger count.
-- =============================================================================

create or replace function public.driver_add_song(
  p_ride_id uuid,
  p_video_id text,
  p_title text,
  p_artist text default null,
  p_duration_seconds integer default null,
  p_source text default 'youtube'
) returns public.song_requests
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := auth.uid();
  v_ride public.rides;
  v_passenger public.passengers;
  v_source public.request_source;
  v_title text := left(nullif(btrim(regexp_replace(coalesce(p_title, ''), '[[:cntrl:]]', '', 'g')), ''), 200);
  v_artist text := left(nullif(btrim(regexp_replace(coalesce(p_artist, ''), '[[:cntrl:]]', '', 'g')), ''), 120);
  v_req public.song_requests;
begin
  if v_uid is null then perform public.taxidj_error('NOT_AUTHENTICATED'); end if;

  select * into v_ride from public.rides
   where id = p_ride_id and driver_id = v_uid
   for update;
  if not found then perform public.taxidj_error('RIDE_NOT_FOUND'); end if;
  if not public.ride_is_open(v_ride) then perform public.taxidj_error('RIDE_ENDED'); end if;

  if p_video_id is null or p_video_id !~ '^[A-Za-z0-9_-]{11}$' then
    perform public.taxidj_error('INVALID_VIDEO');
  end if;

  if exists (
    select 1 from public.song_requests
     where ride_id = v_ride.id and youtube_video_id = p_video_id
       and status in ('pending', 'queued', 'playing')
  ) then
    perform public.taxidj_error('DUPLICATE_REQUEST');
  end if;

  select * into v_passenger from public.passengers
   where ride_id = v_ride.id and session_identifier = v_uid;
  if not found then
    insert into public.passengers (ride_id, session_identifier, nickname)
    values (v_ride.id, v_uid, 'Driver')
    returning * into v_passenger;
  end if;

  v_source := case when p_source = 'youtube_music' then 'youtube_music' else 'youtube' end;

  insert into public.song_requests (
    ride_id, passenger_id, title, artist, thumbnail_url, youtube_url,
    youtube_video_id, source, duration_seconds, status, position
  ) values (
    v_ride.id,
    v_passenger.id,
    coalesce(v_title, 'YouTube video'),
    v_artist,
    'https://i.ytimg.com/vi/' || p_video_id || '/hqdefault.jpg',
    case v_source
      when 'youtube_music' then 'https://music.youtube.com/watch?v=' || p_video_id
      else 'https://www.youtube.com/watch?v=' || p_video_id
    end,
    p_video_id,
    v_source,
    case when p_duration_seconds between 0 and 86400 then p_duration_seconds end,
    'queued',
    (select coalesce(max(position), 0) + 1 from public.song_requests where ride_id = v_ride.id)
  )
  returning * into v_req;

  return v_req;
end;
$$;

revoke execute on function public.driver_add_song(uuid, text, text, text, integer, text) from public, anon, authenticated;
grant execute on function public.driver_add_song(uuid, text, text, text, integer, text) to authenticated;

-- Ride history: don't count the driver's own "Driver" row as a passenger.
create or replace function public.driver_ride_history(p_limit integer default 50)
returns table (
  id uuid,
  join_code text,
  name text,
  status public.ride_status,
  created_at timestamptz,
  ended_at timestamptz,
  expires_at timestamptz,
  passenger_count bigint,
  song_count bigint,
  played_count bigint
)
language sql stable security definer set search_path = '' as $$
  select r.id, r.join_code, r.name, r.status, r.created_at, r.ended_at, r.expires_at,
         (select count(*) from public.passengers p where p.ride_id = r.id and p.session_identifier <> r.driver_id),
         (select count(*) from public.song_requests s where s.ride_id = r.id),
         (select count(*) from public.song_requests s where s.ride_id = r.id and s.status = 'played')
    from public.rides r
   where r.driver_id = auth.uid()
   order by r.created_at desc
   limit least(greatest(coalesce(p_limit, 50), 1), 200);
$$;

-- ---------------------------------------------------------------- 20260930000000_spotify.sql
-- =============================================================================
-- Taxi DJ — songs picked from Spotify
--
-- Riders/drivers can search Spotify. A Spotify pick is stored with its
-- Spotify track (so the driver can open it in the Spotify app) AND the
-- matching YouTube video (so it plays in the in-app player and the YouTube
-- playlist like every other song).
-- =============================================================================

alter table public.song_requests
  add column if not exists spotify_track_id text check (spotify_track_id ~ '^[A-Za-z0-9]{22}$'),
  add column if not exists spotify_url text;

drop function if exists public.add_song_request(uuid, text, text, text, integer, text);
drop function if exists public.driver_add_song(uuid, text, text, text, integer, text);

create or replace function public.add_song_request(
  p_ride_id uuid,
  p_video_id text,
  p_title text,
  p_artist text default null,
  p_duration_seconds integer default null,
  p_source text default 'youtube',
  p_spotify_track_id text default null
) returns public.song_requests
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := auth.uid();
  v_ride public.rides;
  v_passenger public.passengers;
  v_used integer;
  v_source public.request_source;
  v_title text := left(nullif(btrim(regexp_replace(coalesce(p_title, ''), '[[:cntrl:]]', '', 'g')), ''), 200);
  v_artist text := left(nullif(btrim(regexp_replace(coalesce(p_artist, ''), '[[:cntrl:]]', '', 'g')), ''), 120);
  v_req public.song_requests;
begin
  if v_uid is null then perform public.taxidj_error('NOT_AUTHENTICATED'); end if;

  -- Lock the ride so limit/duplicate/position checks are race-free.
  select * into v_ride from public.rides where id = p_ride_id for update;
  if not found then perform public.taxidj_error('RIDE_NOT_FOUND'); end if;

  select * into v_passenger from public.passengers
   where ride_id = v_ride.id and session_identifier = v_uid;
  if not found then perform public.taxidj_error('NOT_A_PASSENGER'); end if;

  if v_ride.status = 'ended' then perform public.taxidj_error('RIDE_ENDED'); end if;
  if v_ride.expires_at <= now() then perform public.taxidj_error('RIDE_EXPIRED'); end if;

  if p_video_id is null or p_video_id !~ '^[A-Za-z0-9_-]{11}$' then
    perform public.taxidj_error('INVALID_VIDEO');
  end if;

  if p_spotify_track_id is not null and p_spotify_track_id !~ '^[A-Za-z0-9]{22}$' then
    perform public.taxidj_error('INVALID_VIDEO');
  end if;

  v_source := case when p_source = 'youtube_music' then 'youtube_music' else 'youtube' end;

  -- Rejected/removed requests don't count toward the limit.
  select count(*) into v_used from public.song_requests
   where passenger_id = v_passenger.id and status not in ('rejected', 'removed');
  if v_used >= v_ride.max_requests_per_passenger then
    perform public.taxidj_error('REQUEST_LIMIT_REACHED');
  end if;

  if exists (
    select 1 from public.song_requests
     where ride_id = v_ride.id and youtube_video_id = p_video_id
       and status in ('pending', 'queued', 'playing')
  ) then
    perform public.taxidj_error('DUPLICATE_REQUEST');
  end if;

  insert into public.song_requests (
    ride_id, passenger_id, title, artist, thumbnail_url, youtube_url,
    youtube_video_id, source, duration_seconds, status, position,
    spotify_track_id, spotify_url
  ) values (
    v_ride.id,
    v_passenger.id,
    coalesce(v_title, 'YouTube video'),
    v_artist,
    'https://i.ytimg.com/vi/' || p_video_id || '/hqdefault.jpg',
    case v_source
      when 'youtube_music' then 'https://music.youtube.com/watch?v=' || p_video_id
      else 'https://www.youtube.com/watch?v=' || p_video_id
    end,
    p_video_id,
    v_source,
    case when p_duration_seconds between 0 and 86400 then p_duration_seconds end,
    case when v_ride.auto_approve then 'queued'::public.request_status else 'pending' end,
    (select coalesce(max(position), 0) + 1 from public.song_requests where ride_id = v_ride.id),
    p_spotify_track_id,
    case when p_spotify_track_id is not null then 'https://open.spotify.com/track/' || p_spotify_track_id end
  )
  returning * into v_req;

  return v_req;
end;
$$;

create or replace function public.driver_add_song(
  p_ride_id uuid,
  p_video_id text,
  p_title text,
  p_artist text default null,
  p_duration_seconds integer default null,
  p_source text default 'youtube',
  p_spotify_track_id text default null
) returns public.song_requests
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := auth.uid();
  v_ride public.rides;
  v_passenger public.passengers;
  v_source public.request_source;
  v_title text := left(nullif(btrim(regexp_replace(coalesce(p_title, ''), '[[:cntrl:]]', '', 'g')), ''), 200);
  v_artist text := left(nullif(btrim(regexp_replace(coalesce(p_artist, ''), '[[:cntrl:]]', '', 'g')), ''), 120);
  v_req public.song_requests;
begin
  if v_uid is null then perform public.taxidj_error('NOT_AUTHENTICATED'); end if;

  select * into v_ride from public.rides
   where id = p_ride_id and driver_id = v_uid
   for update;
  if not found then perform public.taxidj_error('RIDE_NOT_FOUND'); end if;
  if not public.ride_is_open(v_ride) then perform public.taxidj_error('RIDE_ENDED'); end if;

  if p_video_id is null or p_video_id !~ '^[A-Za-z0-9_-]{11}$' then
    perform public.taxidj_error('INVALID_VIDEO');
  end if;

  if p_spotify_track_id is not null and p_spotify_track_id !~ '^[A-Za-z0-9]{22}$' then
    perform public.taxidj_error('INVALID_VIDEO');
  end if;

  if exists (
    select 1 from public.song_requests
     where ride_id = v_ride.id and youtube_video_id = p_video_id
       and status in ('pending', 'queued', 'playing')
  ) then
    perform public.taxidj_error('DUPLICATE_REQUEST');
  end if;

  select * into v_passenger from public.passengers
   where ride_id = v_ride.id and session_identifier = v_uid;
  if not found then
    insert into public.passengers (ride_id, session_identifier, nickname)
    values (v_ride.id, v_uid, 'Driver')
    returning * into v_passenger;
  end if;

  v_source := case when p_source = 'youtube_music' then 'youtube_music' else 'youtube' end;

  insert into public.song_requests (
    ride_id, passenger_id, title, artist, thumbnail_url, youtube_url,
    youtube_video_id, source, duration_seconds, status, position,
    spotify_track_id, spotify_url
  ) values (
    v_ride.id,
    v_passenger.id,
    coalesce(v_title, 'YouTube video'),
    v_artist,
    'https://i.ytimg.com/vi/' || p_video_id || '/hqdefault.jpg',
    case v_source
      when 'youtube_music' then 'https://music.youtube.com/watch?v=' || p_video_id
      else 'https://www.youtube.com/watch?v=' || p_video_id
    end,
    p_video_id,
    v_source,
    case when p_duration_seconds between 0 and 86400 then p_duration_seconds end,
    'queued',
    (select coalesce(max(position), 0) + 1 from public.song_requests where ride_id = v_ride.id),
    p_spotify_track_id,
    case when p_spotify_track_id is not null then 'https://open.spotify.com/track/' || p_spotify_track_id end
  )
  returning * into v_req;

  return v_req;
end;
$$;

revoke execute on function
  public.add_song_request(uuid, text, text, text, integer, text, text),
  public.driver_add_song(uuid, text, text, text, integer, text, text)
from public, anon, authenticated;
grant execute on function
  public.add_song_request(uuid, text, text, text, integer, text, text),
  public.driver_add_song(uuid, text, text, text, integer, text, text)
to authenticated;

-- ---------------------------------------------------------------- 20261001000000_car_qr.sql
-- =============================================================================
-- Taxi DJ — permanent car QR code + removing passengers
--
-- Car QR code
-- * Each driver gets a permanent car_code (8 characters). A printed QR code
--   for /c/<car_code> always leads to the driver's ride that is running now.
-- * resolve_car_code() is public: it returns the current ride's join code,
--   or "no_ride" when the driver has no ride running. Every ride still has
--   its own join code, and an ended ride can't be joined or added to.
-- * reset_car_code() gives the driver a new code; old printed cards stop
--   working.
--
-- Removing passengers
-- * driver_remove_passenger() removes someone from the ride (e.g. a former
--   passenger who kept the car QR code): their waiting songs are removed and
--   they can't add songs, see the ride, or join it again.
-- =============================================================================

alter table public.drivers
  add column if not exists car_code text unique check (car_code ~ '^[A-HJ-NP-Z2-9]{8}$');

alter table public.passengers add column if not exists removed_at timestamptz;

-- ---------------------------------------------------------------------------
-- Car code
-- ---------------------------------------------------------------------------

create or replace function public.new_car_code() returns text
language plpgsql volatile set search_path = '' as $$
declare
  v_alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  v_code text := '';
begin
  for i in 1..8 loop
    v_code := v_code || substr(v_alphabet, 1 + floor(random() * length(v_alphabet))::int, 1);
  end loop;
  return v_code;
end;
$$;

-- Returns the driver's car code, creating it on first use (or always a new
-- one when p_reset is true).
create or replace function public.driver_car_code(p_reset boolean default false) returns text
language plpgsql security definer set search_path = '' as $$
declare
  v_driver public.drivers;
  v_attempt integer := 0;
begin
  v_driver := public.ensure_driver();
  if v_driver.car_code is not null and not coalesce(p_reset, false) then
    return v_driver.car_code;
  end if;
  loop
    v_attempt := v_attempt + 1;
    begin
      update public.drivers set car_code = public.new_car_code()
       where id = v_driver.id
      returning * into v_driver;
      return v_driver.car_code;
    exception when unique_violation then
      if v_attempt >= 20 then perform public.taxidj_error('CODE_GENERATION_FAILED'); end if;
    end;
  end loop;
end;
$$;

-- Public: where does this car's QR code lead right now?
--   state 'active'  → join_code of the ride running now
--   state 'no_ride' → the driver has no ride running
--   no row          → unknown / replaced code
create or replace function public.resolve_car_code(p_code text)
returns table (state text, join_code text, name text)
language sql stable security definer set search_path = '' as $$
  select case when r.id is null then 'no_ride' else 'active' end,
         r.join_code,
         coalesce(r.name, d.display_name)
    from public.drivers d
    left join public.rides r
      on r.driver_id = d.id and r.status = 'active' and r.expires_at > now()
   where d.car_code = upper(btrim(p_code))
   limit 1;
$$;

-- ---------------------------------------------------------------------------
-- Removing passengers
-- ---------------------------------------------------------------------------

-- Removed passengers no longer count as ride members (reading the ride and
-- its queue).
create or replace function public.is_ride_passenger(p_ride_id uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.passengers p
    where p.ride_id = p_ride_id and p.session_identifier = auth.uid() and p.removed_at is null
  );
$$;

-- Removed passengers can't add songs (covers every insert path).
create or replace function public.song_requests_block_removed() returns trigger
language plpgsql set search_path = '' as $$
begin
  if exists (select 1 from public.passengers where id = new.passenger_id and removed_at is not null) then
    perform public.taxidj_error('PASSENGER_REMOVED');
  end if;
  return new;
end;
$$;

drop trigger if exists song_requests_block_removed on public.song_requests;
create trigger song_requests_block_removed
  before insert on public.song_requests
  for each row execute function public.song_requests_block_removed();

create or replace function public.driver_remove_passenger(p_passenger_id uuid) returns public.passengers
language plpgsql security definer set search_path = '' as $$
declare
  v_passenger public.passengers;
  v_ride public.rides;
begin
  select * into v_passenger from public.passengers where id = p_passenger_id;
  if not found then perform public.taxidj_error('PASSENGER_NOT_FOUND'); end if;

  select * into v_ride from public.rides
   where id = v_passenger.ride_id and driver_id = auth.uid()
   for update;
  if not found then perform public.taxidj_error('PASSENGER_NOT_FOUND'); end if;
  -- The driver's own row (songs the driver added) can't be removed.
  if v_passenger.session_identifier = v_ride.driver_id then
    perform public.taxidj_error('INVALID_ACTION');
  end if;

  update public.passengers set removed_at = coalesce(removed_at, now())
   where id = v_passenger.id
  returning * into v_passenger;

  -- Their songs that haven't played yet leave the queue.
  update public.song_requests set status = 'removed'
   where passenger_id = v_passenger.id and status in ('pending', 'queued');

  return v_passenger;
end;
$$;

-- join_ride: unchanged, except a removed passenger can't join again.
create or replace function public.join_ride(p_code text, p_nickname text default null)
returns public.passengers
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := auth.uid();
  v_ride public.rides;
  v_passenger public.passengers;
  v_nickname text := nullif(btrim(coalesce(p_nickname, '')), '');
begin
  if v_uid is null then perform public.taxidj_error('NOT_AUTHENTICATED'); end if;

  select * into v_ride from public.rides where join_code = upper(btrim(p_code)) for update;
  if not found then perform public.taxidj_error('RIDE_NOT_FOUND'); end if;
  if v_ride.status = 'ended' then perform public.taxidj_error('RIDE_ENDED'); end if;
  if v_ride.expires_at <= now() then perform public.taxidj_error('RIDE_EXPIRED'); end if;

  if v_nickname is not null and char_length(v_nickname) > 30 then
    v_nickname := left(v_nickname, 30);
  end if;

  select * into v_passenger from public.passengers
   where ride_id = v_ride.id and session_identifier = v_uid;

  if found then
    if v_passenger.removed_at is not null then
      perform public.taxidj_error('PASSENGER_REMOVED');
    end if;
    if v_nickname is not null and v_nickname <> v_passenger.nickname then
      update public.passengers set nickname = v_nickname
       where id = v_passenger.id returning * into v_passenger;
    end if;
    return v_passenger;
  end if;

  if v_nickname is null then
    select 'Passenger ' || (count(*) + 1) into v_nickname
      from public.passengers where ride_id = v_ride.id;
  end if;

  insert into public.passengers (ride_id, session_identifier, nickname)
  values (v_ride.id, v_uid, v_nickname)
  returning * into v_passenger;

  return v_passenger;
end;
$$;

revoke execute on function
  public.new_car_code(),
  public.driver_car_code(boolean),
  public.resolve_car_code(text),
  public.driver_remove_passenger(uuid),
  public.song_requests_block_removed()
from public, anon, authenticated;

grant execute on function public.driver_car_code(boolean), public.driver_remove_passenger(uuid) to authenticated;
-- Anyone who scans the car QR code (before signing in) can resolve it.
grant execute on function public.resolve_car_code(text) to anon, authenticated;

-- ---------------------------------------------------------------- 20261002000000_push_notifications.sql
-- =============================================================================
-- Taxi DJ — push notifications for drivers
--
-- * push_subscriptions: a driver's devices that should get a notification
--   when a passenger adds a song (Web Push; one row per browser/device).
--   Drivers manage their own rows through the functions below; the server
--   (service role) reads them to send notifications.
-- * song_requests.push_sent_at: set once a notification has been sent for
--   a request, so it's never sent twice.
-- =============================================================================

create table if not exists public.push_subscriptions (
  id          uuid primary key default gen_random_uuid(),
  driver_id   uuid not null references public.drivers (id) on delete cascade,
  endpoint    text not null unique check (endpoint ~ '^https://' and char_length(endpoint) <= 1000),
  p256dh      text not null check (char_length(p256dh) between 20 and 200),
  auth        text not null check (char_length(auth) between 8 and 100),
  created_at  timestamptz not null default now()
);

create index if not exists push_subscriptions_driver_idx on public.push_subscriptions (driver_id);

alter table public.push_subscriptions enable row level security;
revoke all on public.push_subscriptions from anon, authenticated;
grant select on public.push_subscriptions to authenticated;

drop policy if exists "Drivers read their own push subscriptions" on public.push_subscriptions;
create policy "Drivers read their own push subscriptions"
  on public.push_subscriptions for select to authenticated
  using (driver_id = auth.uid());

alter table public.song_requests add column if not exists push_sent_at timestamptz;

-- Saves this device's subscription for the signed-in driver (moves it over
-- if the device was used by another account before).
create or replace function public.save_push_subscription(p_endpoint text, p_p256dh text, p_auth text)
returns void
language plpgsql security definer set search_path = '' as $$
declare
  v_driver public.drivers;
begin
  v_driver := public.ensure_driver();
  insert into public.push_subscriptions (driver_id, endpoint, p256dh, auth)
  values (v_driver.id, p_endpoint, p_p256dh, p_auth)
  on conflict (endpoint) do update
    set driver_id = excluded.driver_id, p256dh = excluded.p256dh, auth = excluded.auth;
end;
$$;

create or replace function public.delete_push_subscription(p_endpoint text)
returns void
language sql security definer set search_path = '' as $$
  delete from public.push_subscriptions where endpoint = p_endpoint and driver_id = auth.uid();
$$;

revoke execute on function
  public.save_push_subscription(text, text, text),
  public.delete_push_subscription(text)
from public, anon, authenticated;
grant execute on function
  public.save_push_subscription(text, text, text),
  public.delete_push_subscription(text)
to authenticated;

-- ---------------------------------------------------------------- 20261004000000_soundcloud.sql
-- =============================================================================
-- Taxi DJ — SoundCloud songs (play like the radio: plain audio, background)
--
-- * song_requests.provider: 'youtube' (default, as before) or 'soundcloud'.
--   SoundCloud songs have soundcloud_track_id + soundcloud_url and no
--   YouTube video; they're streamed in the browser from SoundCloud's own
--   stream URL at play time (nothing stored or downloaded).
-- * add_soundcloud_request() / driver_add_soundcloud_song(): same rules as
--   YouTube songs (limits, approval, duplicates, ride open).
-- * song_media_key(): one identity for "same song" across providers, used
--   by duplicate checks and "previous song".
-- =============================================================================

alter table public.song_requests
  add column if not exists provider text not null default 'youtube',
  add column if not exists soundcloud_track_id text,
  add column if not exists soundcloud_url text;

alter table public.song_requests drop constraint if exists song_requests_provider_check;
alter table public.song_requests add constraint song_requests_provider_check
  check (provider in ('youtube', 'soundcloud'));

alter table public.song_requests alter column youtube_video_id drop not null;
alter table public.song_requests alter column youtube_url drop not null;

alter table public.song_requests drop constraint if exists song_requests_media_check;
alter table public.song_requests add constraint song_requests_media_check check (
  (provider = 'youtube' and youtube_video_id is not null and youtube_url is not null)
  or (
    provider = 'soundcloud'
    and youtube_video_id is null
    and soundcloud_track_id ~ '^[0-9]{1,20}$'
    and soundcloud_url ~ '^https://soundcloud\.com/[^[:space:]]+$'
  )
);

create unique index if not exists song_requests_no_active_sc_duplicates
  on public.song_requests (ride_id, soundcloud_track_id)
  where status in ('pending', 'queued', 'playing') and soundcloud_track_id is not null;

create or replace function public.song_media_key(r public.song_requests) returns text
language sql immutable set search_path = '' as $$
  select case when r.provider = 'soundcloud' then 'sc:' || r.soundcloud_track_id else 'yt:' || r.youtube_video_id end;
$$;

-- Shared checks for a SoundCloud pick.
create or replace function public.soundcloud_args_ok(p_track_id text, p_url text, p_artwork text) returns boolean
language sql immutable set search_path = '' as $$
  select coalesce(p_track_id ~ '^[0-9]{1,20}$', false)
     and coalesce(p_url ~ '^https://soundcloud\.com/[^[:space:]]{1,250}$', false)
     and (p_artwork is null or p_artwork ~ '^https://[a-z0-9-]+\.sndcdn\.com/[^[:space:]]{1,250}$');
$$;

create or replace function public.add_soundcloud_request(
  p_ride_id uuid,
  p_track_id text,
  p_title text,
  p_artist text default null,
  p_duration_seconds integer default null,
  p_url text default null,
  p_artwork_url text default null
) returns public.song_requests
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := auth.uid();
  v_ride public.rides;
  v_passenger public.passengers;
  v_used integer;
  v_title text := left(nullif(btrim(regexp_replace(coalesce(p_title, ''), '[[:cntrl:]]', '', 'g')), ''), 200);
  v_artist text := left(nullif(btrim(regexp_replace(coalesce(p_artist, ''), '[[:cntrl:]]', '', 'g')), ''), 120);
  v_req public.song_requests;
begin
  if v_uid is null then perform public.taxidj_error('NOT_AUTHENTICATED'); end if;

  select * into v_ride from public.rides where id = p_ride_id for update;
  if not found then perform public.taxidj_error('RIDE_NOT_FOUND'); end if;

  select * into v_passenger from public.passengers
   where ride_id = v_ride.id and session_identifier = v_uid;
  if not found then perform public.taxidj_error('NOT_A_PASSENGER'); end if;

  if v_ride.status = 'ended' then perform public.taxidj_error('RIDE_ENDED'); end if;
  if v_ride.expires_at <= now() then perform public.taxidj_error('RIDE_EXPIRED'); end if;
  if not public.soundcloud_args_ok(p_track_id, p_url, p_artwork_url) then
    perform public.taxidj_error('INVALID_VIDEO');
  end if;

  select count(*) into v_used from public.song_requests
   where passenger_id = v_passenger.id and status not in ('rejected', 'removed');
  if v_used >= v_ride.max_requests_per_passenger then
    perform public.taxidj_error('REQUEST_LIMIT_REACHED');
  end if;

  if exists (
    select 1 from public.song_requests
     where ride_id = v_ride.id and soundcloud_track_id = p_track_id
       and status in ('pending', 'queued', 'playing')
  ) then
    perform public.taxidj_error('DUPLICATE_REQUEST');
  end if;

  insert into public.song_requests (
    ride_id, passenger_id, title, artist, thumbnail_url, youtube_url, youtube_video_id,
    provider, soundcloud_track_id, soundcloud_url, duration_seconds, status, position
  ) values (
    v_ride.id, v_passenger.id, coalesce(v_title, 'SoundCloud track'), v_artist,
    coalesce(p_artwork_url, '/icons/512'), null, null,
    'soundcloud', p_track_id, p_url,
    case when p_duration_seconds between 0 and 86400 then p_duration_seconds end,
    case when v_ride.auto_approve then 'queued'::public.request_status else 'pending' end,
    (select coalesce(max(position), 0) + 1 from public.song_requests where ride_id = v_ride.id)
  )
  returning * into v_req;
  return v_req;
end;
$$;

create or replace function public.driver_add_soundcloud_song(
  p_ride_id uuid,
  p_track_id text,
  p_title text,
  p_artist text default null,
  p_duration_seconds integer default null,
  p_url text default null,
  p_artwork_url text default null
) returns public.song_requests
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := auth.uid();
  v_ride public.rides;
  v_passenger public.passengers;
  v_title text := left(nullif(btrim(regexp_replace(coalesce(p_title, ''), '[[:cntrl:]]', '', 'g')), ''), 200);
  v_artist text := left(nullif(btrim(regexp_replace(coalesce(p_artist, ''), '[[:cntrl:]]', '', 'g')), ''), 120);
  v_req public.song_requests;
begin
  if v_uid is null then perform public.taxidj_error('NOT_AUTHENTICATED'); end if;

  select * into v_ride from public.rides where id = p_ride_id and driver_id = v_uid for update;
  if not found then perform public.taxidj_error('RIDE_NOT_FOUND'); end if;
  if not public.ride_is_open(v_ride) then perform public.taxidj_error('RIDE_ENDED'); end if;
  if not public.soundcloud_args_ok(p_track_id, p_url, p_artwork_url) then
    perform public.taxidj_error('INVALID_VIDEO');
  end if;

  if exists (
    select 1 from public.song_requests
     where ride_id = v_ride.id and soundcloud_track_id = p_track_id
       and status in ('pending', 'queued', 'playing')
  ) then
    perform public.taxidj_error('DUPLICATE_REQUEST');
  end if;

  select * into v_passenger from public.passengers
   where ride_id = v_ride.id and session_identifier = v_uid;
  if not found then
    insert into public.passengers (ride_id, session_identifier, nickname)
    values (v_ride.id, v_uid, 'Driver')
    returning * into v_passenger;
  end if;

  insert into public.song_requests (
    ride_id, passenger_id, title, artist, thumbnail_url, youtube_url, youtube_video_id,
    provider, soundcloud_track_id, soundcloud_url, duration_seconds, status, position
  ) values (
    v_ride.id, v_passenger.id, coalesce(v_title, 'SoundCloud track'), v_artist,
    coalesce(p_artwork_url, '/icons/512'), null, null,
    'soundcloud', p_track_id, p_url,
    case when p_duration_seconds between 0 and 86400 then p_duration_seconds end,
    'queued',
    (select coalesce(max(position), 0) + 1 from public.song_requests where ride_id = v_ride.id)
  )
  returning * into v_req;
  return v_req;
end;
$$;

-- "Previous song" and the replay duplicate check now compare songs across
-- providers (otherwise unchanged).
create or replace function public.driver_skip(p_ride_id uuid, p_direction text)
returns public.song_requests
language plpgsql security definer set search_path = '' as $$
declare
  v_ride public.rides;
  v_current public.song_requests;
  v_target public.song_requests;
  v_min_pos integer;
begin
  select * into v_ride from public.rides
   where id = p_ride_id and driver_id = auth.uid()
   for update;
  if not found then perform public.taxidj_error('RIDE_NOT_FOUND'); end if;
  if not public.ride_is_open(v_ride) then perform public.taxidj_error('RIDE_ENDED'); end if;

  select * into v_current from public.song_requests
   where ride_id = p_ride_id and status = 'playing';

  if p_direction = 'next' then
    if v_current.id is not null then
      update public.song_requests set status = 'played' where id = v_current.id;
    end if;
    select * into v_target from public.song_requests
     where ride_id = p_ride_id and status = 'queued'
     order by position asc limit 1;

  elsif p_direction = 'previous' then
    select * into v_target from public.song_requests
     where ride_id = p_ride_id and status = 'played'
       and public.song_media_key(song_requests) is distinct from public.song_media_key(v_current)
       and not exists (
         select 1 from public.song_requests d
          where d.ride_id = p_ride_id
            and public.song_media_key(d) = public.song_media_key(song_requests)
            and d.status in ('pending', 'queued')
       )
     order by coalesce(started_at, updated_at) desc limit 1;
    if v_target.id is null then
      return v_current; -- nothing to go back to
    end if;
    if v_current.id is not null then
      select coalesce(min(position), 0) into v_min_pos from public.song_requests
       where ride_id = p_ride_id and status in ('pending', 'queued');
      update public.song_requests
         set status = 'queued', started_at = null, position = least(v_min_pos, v_current.position) - 1
       where id = v_current.id;
    end if;

  else
    perform public.taxidj_error('INVALID_ACTION');
  end if;

  if v_target.id is null then
    return null;
  end if;

  update public.song_requests set status = 'playing', started_at = now()
   where id = v_target.id returning * into v_target;
  return v_target;
end;
$$;

create or replace function public.driver_update_request(p_request_id uuid, p_action text)
returns public.song_requests
language plpgsql security definer set search_path = '' as $$
declare
  v_req public.song_requests;
  v_ride public.rides;
  v_other public.song_requests;
  v_pos integer;
begin
  select * into v_req from public.song_requests where id = p_request_id;
  if not found then perform public.taxidj_error('REQUEST_NOT_FOUND'); end if;

  -- Lock the ride: serialises all queue changes for this ride.
  select * into v_ride from public.rides
   where id = v_req.ride_id and driver_id = auth.uid()
   for update;
  if not found then perform public.taxidj_error('REQUEST_NOT_FOUND'); end if;
  if not public.ride_is_open(v_ride) then perform public.taxidj_error('RIDE_ENDED'); end if;

  -- Re-read under the ride lock.
  select * into v_req from public.song_requests where id = p_request_id;

  case p_action
    when 'approve' then
      if v_req.status <> 'pending' then perform public.taxidj_error('INVALID_TRANSITION'); end if;
      update public.song_requests set status = 'queued' where id = v_req.id returning * into v_req;

    when 'reject' then
      if v_req.status <> 'pending' then perform public.taxidj_error('INVALID_TRANSITION'); end if;
      update public.song_requests set status = 'rejected' where id = v_req.id returning * into v_req;

    when 'remove' then
      -- Drivers can remove any song from the ride's list, including played ones.
      if v_req.status not in ('pending', 'queued', 'playing', 'played') then
        perform public.taxidj_error('INVALID_TRANSITION');
      end if;
      update public.song_requests set status = 'removed' where id = v_req.id returning * into v_req;

    when 'play' then
      if v_req.status not in ('pending', 'queued', 'played') then
        perform public.taxidj_error('INVALID_TRANSITION');
      end if;
      if v_req.status = 'played' and exists (
        select 1 from public.song_requests
         where ride_id = v_req.ride_id and public.song_media_key(song_requests) = public.song_media_key(v_req)
           and status in ('pending', 'queued') and id <> v_req.id
      ) then
        perform public.taxidj_error('DUPLICATE_REQUEST');
      end if;
      update public.song_requests set status = 'played'
       where ride_id = v_req.ride_id and status = 'playing';
      update public.song_requests set status = 'playing', started_at = now()
       where id = v_req.id returning * into v_req;

    when 'finish' then
      if v_req.status <> 'playing' then perform public.taxidj_error('INVALID_TRANSITION'); end if;
      update public.song_requests set status = 'played' where id = v_req.id returning * into v_req;

    when 'move_up', 'move_down' then
      if v_req.status not in ('pending', 'queued') then perform public.taxidj_error('INVALID_TRANSITION'); end if;
      if p_action = 'move_up' then
        select * into v_other from public.song_requests
         where ride_id = v_req.ride_id and status in ('pending', 'queued')
           and position < v_req.position
         order by position desc limit 1;
      else
        select * into v_other from public.song_requests
         where ride_id = v_req.ride_id and status in ('pending', 'queued')
           and position > v_req.position
         order by position asc limit 1;
      end if;
      if found then
        v_pos := v_req.position;
        update public.song_requests set position = v_other.position where id = v_req.id
          returning * into v_req;
        update public.song_requests set position = v_pos where id = v_other.id;
      end if;

    else
      perform public.taxidj_error('INVALID_ACTION');
  end case;

  return v_req;
end;
$$;

revoke execute on function
  public.add_soundcloud_request(uuid, text, text, text, integer, text, text),
  public.driver_add_soundcloud_song(uuid, text, text, text, integer, text, text),
  public.soundcloud_args_ok(text, text, text),
  public.song_media_key(public.song_requests)
from public, anon, authenticated;
grant execute on function
  public.add_soundcloud_request(uuid, text, text, text, integer, text, text),
  public.driver_add_soundcloud_song(uuid, text, text, text, integer, text, text)
to authenticated;

-- ---------------------------------------------------------------- 20261007000000_audio_links.sql
-- =============================================================================
-- Taxi DJ — audio file links (Google Drive, Dropbox or any https audio file)
--
-- * song_requests.provider gains 'audio': the song is an audio file the
--   driver or a passenger keeps online. audio_url is the file's address; the
--   driver's phone plays it directly in a plain audio player (like the
--   radio). Nothing is uploaded to or stored by Taxi DJ.
-- * add_audio_link_request() / driver_add_audio_link(): same rules as other
--   songs (limits, approval, duplicates, ride open).
-- * song_media_key() also knows audio links ("same song" = same address).
-- =============================================================================

alter table public.song_requests add column if not exists audio_url text;

alter table public.song_requests drop constraint if exists song_requests_provider_check;
alter table public.song_requests add constraint song_requests_provider_check
  check (provider in ('youtube', 'soundcloud', 'audio'));

-- A secure, public web address: https, no spaces, not the phone itself or a
-- home/office network, at most 2000 bytes.
create or replace function public.audio_link_ok(p_url text) returns boolean
language sql immutable set search_path = '' as $$
  select coalesce(
    octet_length(p_url) <= 2000
    and p_url ~* '^https://[a-z0-9.-]+\.[a-z0-9-]+(:[0-9]{1,5})?/[^[:space:]]*$'
    and p_url !~* '^https://(localhost|0\.|10\.|127\.|169\.254\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[01])\.|100\.(6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\.)'
    and p_url !~* '^https://[^/]*\.(local|localhost|internal|lan|home|intranet)(:[0-9]+)?/',
    false);
$$;

alter table public.song_requests drop constraint if exists song_requests_media_check;
alter table public.song_requests add constraint song_requests_media_check check (
  (provider = 'youtube' and youtube_video_id is not null and youtube_url is not null)
  or (
    provider = 'soundcloud'
    and youtube_video_id is null
    and soundcloud_track_id ~ '^[0-9]{1,20}$'
    and soundcloud_url ~ '^https://soundcloud\.com/[^[:space:]]+$'
  )
  or (
    provider = 'audio'
    and youtube_video_id is null
    and soundcloud_track_id is null
    and public.audio_link_ok(audio_url)
  )
);

create unique index if not exists song_requests_no_active_audio_duplicates
  on public.song_requests (ride_id, audio_url)
  where status in ('pending', 'queued', 'playing') and audio_url is not null;

create or replace function public.song_media_key(r public.song_requests) returns text
language sql immutable set search_path = '' as $$
  select case r.provider
    when 'soundcloud' then 'sc:' || r.soundcloud_track_id
    when 'audio' then 'au:' || r.audio_url
    else 'yt:' || r.youtube_video_id
  end;
$$;

create or replace function public.add_audio_link_request(
  p_ride_id uuid,
  p_url text,
  p_title text,
  p_artist text default null,
  p_duration_seconds integer default null
) returns public.song_requests
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := auth.uid();
  v_ride public.rides;
  v_passenger public.passengers;
  v_used integer;
  v_title text := left(nullif(btrim(regexp_replace(coalesce(p_title, ''), '[[:cntrl:]]', '', 'g')), ''), 200);
  v_artist text := left(nullif(btrim(regexp_replace(coalesce(p_artist, ''), '[[:cntrl:]]', '', 'g')), ''), 120);
  v_req public.song_requests;
begin
  if v_uid is null then perform public.taxidj_error('NOT_AUTHENTICATED'); end if;

  select * into v_ride from public.rides where id = p_ride_id for update;
  if not found then perform public.taxidj_error('RIDE_NOT_FOUND'); end if;

  select * into v_passenger from public.passengers
   where ride_id = v_ride.id and session_identifier = v_uid;
  if not found then perform public.taxidj_error('NOT_A_PASSENGER'); end if;

  if v_ride.status = 'ended' then perform public.taxidj_error('RIDE_ENDED'); end if;
  if v_ride.expires_at <= now() then perform public.taxidj_error('RIDE_EXPIRED'); end if;
  if not public.audio_link_ok(p_url) then perform public.taxidj_error('INVALID_VIDEO'); end if;

  select count(*) into v_used from public.song_requests
   where passenger_id = v_passenger.id and status not in ('rejected', 'removed');
  if v_used >= v_ride.max_requests_per_passenger then
    perform public.taxidj_error('REQUEST_LIMIT_REACHED');
  end if;

  if exists (
    select 1 from public.song_requests
     where ride_id = v_ride.id and audio_url = p_url
       and status in ('pending', 'queued', 'playing')
  ) then
    perform public.taxidj_error('DUPLICATE_REQUEST');
  end if;

  insert into public.song_requests (
    ride_id, passenger_id, title, artist, thumbnail_url, youtube_url, youtube_video_id,
    provider, audio_url, duration_seconds, status, position
  ) values (
    v_ride.id, v_passenger.id, coalesce(v_title, 'Audio file'), v_artist,
    '/icons/512', null, null,
    'audio', p_url, case when p_duration_seconds between 0 and 86400 then p_duration_seconds end,
    case when v_ride.auto_approve then 'queued'::public.request_status else 'pending' end,
    (select coalesce(max(position), 0) + 1 from public.song_requests where ride_id = v_ride.id)
  )
  returning * into v_req;
  return v_req;
end;
$$;

create or replace function public.driver_add_audio_link(
  p_ride_id uuid,
  p_url text,
  p_title text,
  p_artist text default null,
  p_duration_seconds integer default null
) returns public.song_requests
language plpgsql security definer set search_path = '' as $$
declare
  v_uid uuid := auth.uid();
  v_ride public.rides;
  v_passenger public.passengers;
  v_title text := left(nullif(btrim(regexp_replace(coalesce(p_title, ''), '[[:cntrl:]]', '', 'g')), ''), 200);
  v_artist text := left(nullif(btrim(regexp_replace(coalesce(p_artist, ''), '[[:cntrl:]]', '', 'g')), ''), 120);
  v_req public.song_requests;
begin
  if v_uid is null then perform public.taxidj_error('NOT_AUTHENTICATED'); end if;

  select * into v_ride from public.rides where id = p_ride_id and driver_id = v_uid for update;
  if not found then perform public.taxidj_error('RIDE_NOT_FOUND'); end if;
  if not public.ride_is_open(v_ride) then perform public.taxidj_error('RIDE_ENDED'); end if;
  if not public.audio_link_ok(p_url) then perform public.taxidj_error('INVALID_VIDEO'); end if;

  if exists (
    select 1 from public.song_requests
     where ride_id = v_ride.id and audio_url = p_url
       and status in ('pending', 'queued', 'playing')
  ) then
    perform public.taxidj_error('DUPLICATE_REQUEST');
  end if;

  select * into v_passenger from public.passengers
   where ride_id = v_ride.id and session_identifier = v_uid;
  if not found then
    insert into public.passengers (ride_id, session_identifier, nickname)
    values (v_ride.id, v_uid, 'Driver')
    returning * into v_passenger;
  end if;

  insert into public.song_requests (
    ride_id, passenger_id, title, artist, thumbnail_url, youtube_url, youtube_video_id,
    provider, audio_url, duration_seconds, status, position
  ) values (
    v_ride.id, v_passenger.id, coalesce(v_title, 'Audio file'), v_artist,
    '/icons/512', null, null,
    'audio', p_url, case when p_duration_seconds between 0 and 86400 then p_duration_seconds end,
    'queued',
    (select coalesce(max(position), 0) + 1 from public.song_requests where ride_id = v_ride.id)
  )
  returning * into v_req;
  return v_req;
end;
$$;

revoke execute on function
  public.add_audio_link_request(uuid, text, text, text, integer),
  public.driver_add_audio_link(uuid, text, text, text, integer)
from public, anon, authenticated;
grant execute on function
  public.add_audio_link_request(uuid, text, text, text, integer),
  public.driver_add_audio_link(uuid, text, text, text, integer)
to authenticated;

-- Tell the API about any new or changed functions.
notify pgrst, 'reload schema';
